version: "3.8"
services:
  backend:
    build: ./backend
    image: "${DOCKER_USERNAME}/demo-exam-app:backend"
    ports:
      - "8000:8000"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    image: "${DOCKER_USERNAME}/demo-exam-app:frontend"
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
