#!/bin/bash

echo "🔧 Instructions to Fix Jenkins Job Type"
echo "========================================"
echo ""
echo "Your job 'demo_devops' is currently a FREESTYLE project."
echo "Jenkinsfile only works with PIPELINE projects."
echo ""
echo "📋 MANUAL STEPS REQUIRED:"
echo ""
echo "1. CREATE NEW PIPELINE JOB:"
echo "   • Go to: http://jenkins.local/view/all/newJob"
echo "   • Name: demo_devops (or demo_devops-pipeline)"
echo "   • Select: ⭕ Pipeline (NOT Freestyle project)"
echo "   • Click OK"
echo ""
echo "2. CONFIGURE PIPELINE:"
echo "   • Pipeline definition: Pipeline script from SCM"
echo "   • SCM: Git"
echo "   • Repository URL: https://github.com/SeoulX/demo_devops.git"
echo "   • Credentials: demo-app-git"
echo "   • Branch: */main"
echo "   • Script Path: Jenkinsfile"
echo ""
echo "3. SAVE AND TEST:"
echo "   • Click Save"
echo "   • Click 'Build Now' to test"
echo "   • Watch the build - you should see all stages (Build, Test, Deploy)"
echo ""
echo "4. DELETE OLD FREESTYLE JOB (optional):"
echo "   • Go to: http://jenkins.local/job/demo_devops/configure"
echo "   • Scroll to bottom: Delete Project"
echo ""
echo "========================================"
echo ""
echo "After creating the Pipeline job, the webhook will work correctly!"
echo "Webhook URL will be:"
echo "http://jenkins.local/generic-webhook-trigger/invoke?token=demo-devops-token"
echo ""

