#!/bin/bash

echo "🚀 Quick Pipeline Plugin Installation"
echo "====================================="
echo ""

JENKINS_URL="http://jenkins.local"

echo "Option 1: Install via Browser (EASIEST)"
echo "----------------------------------------"
echo ""
echo "1. Open this URL in your browser:"
echo "   $JENKINS_URL/pluginManager/install?plugin.0=pipeline"
echo ""
echo "2. Jenkins will install the plugin automatically"
echo ""
echo "3. After installation, restart Jenkins:"
echo "   $JENKINS_URL/safeRestart"
echo ""
echo "4. Wait for restart, then go to New Item"
echo "   You should see 'Pipeline' option! ✅"
echo ""

echo "Option 2: Install via Plugin Manager"
echo "-------------------------------------"
echo ""
echo "1. Go to: $JENKINS_URL/pluginManager/available"
echo ""
echo "2. Search for: 'Pipeline'"
echo ""
echo "3. Check the box next to 'Pipeline' plugin"
echo ""
echo "4. Click 'Install without restart' or 'Download now and install after restart'"
echo ""
echo "5. Restart Jenkins if prompted"
echo ""

echo "Option 3: Direct Installation (Advanced)"
echo "----------------------------------------"
echo ""
echo "If you have access to Jenkins server:"
echo ""
echo "1. SSH into Jenkins server"
echo ""
echo "2. Download plugin manually:"
echo "   wget https://updates.jenkins.io/download/plugins/pipeline/latest/pipeline.hpi -O /var/jenkins_home/plugins/pipeline.hpi"
echo ""
echo "3. Restart Jenkins"
echo ""

echo "====================================="
echo ""
echo "After installation, the 'Pipeline' option will appear!"
echo "Then follow: CREATE_PIPELINE_JOB.md"
echo ""

