apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-backend
  namespace: ${K8S_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-devops-backend
  template:
    metadata:
      labels:
        app: demo-devops-backend
    spec:
      containers:
      - name: backend
        image: ${BACKEND_IMAGE}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MONGODB_URL
          value: "mongodb://admin:password123@mongodb-svc.${K8S_NAMESPACE}.svc.cluster.local:27017/demo_devops?authSource=admin"
        - name: DATABASE_NAME
          value: "demo_devops"
        livenessProbe:
          httpGet:
            path: /fastapi/get_init
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /fastapi/get_init
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-devops-backend-svc
  namespace: ${K8S_NAMESPACE}
spec:
  selector:
    app: demo-devops-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP

