name: CI/CD Pileline

on:
  push:
    branches:
      - feature-branch
  pull_request:
    branches:
      - feature-branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: 
        python -m venv .venv
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt

    - name: Run tests FastAPI
      run: 
        source .venv/bin/activate
        pytest 
    
    - name: Setup tests NextJS
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies NextJS
      run: 
        cd frontend
        npm install
    
    - name: Run tests NextJS
      run: 
        cd frontend
        npm run test
